import Head from "next/head";
import { useColorScheme } from "@mui/material";

import NavBar from "@/components/NavBar";
import Typography from "@mui/material/Typography";

export default function Home() {
  // const { mode, setMode } = useColorScheme();
  // if (!mode) {
  //   return null;
  // }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <NavBar />
      </header>
      <main>
        
      </main>
    </>
  );
}
